secrets:
  postgres_db:
  # The database's name.
    file: ./docker/secrets/postgres/db.secret
  postgres_password:
  # The database's password.
    file: ./docker/secrets/postgres/password.secret
  postgres_user:
  # The database's default user.
    file: ./docker/secrets/postgres/user.secret
services:
  postgres:
  # This runs the database that everything else connects to
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: postgres:13.2-alpine@sha256:59f48f15d037cc4ac87557cdb69fc9e5891b8a4b8d95254b7030dff561d6fd3a
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    restart: on-failure
  
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    image: mongo
    volumes: 
      - mongo_data:/data/db
    ports: 
      - "27017:27017"
    restart: on-failure

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: on-failure
  
  mongoclient:
    environment: 
      MONGO_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/?retryWrites=true&w=majority
    image: mongoclient/mongoclient
    volumes: 
      - mongoclient_data:/data/db
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
    links: 
      - mongo
    restart: on-failure
  
version: "3.7"
volumes:
  postgres_data:
  # The database's data.
    {}
  pgadmin_data:
  # The pgadmin's data.
    {}
  mongo_data:
    {}
  mongoclient_data:
    {}
